name: Go Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Go 1.23 环境
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    # 安装依赖
    - name: Install dependencies
      run: go mod tidy

    # 编译 Go 程序
    - name: Build
      run: go build -o HeartSync cmd/main.go

    # 上传编译产物作为 Artifact
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: HeartSync # Artifact 名称
        path: ./HeartSync      # 指定编译的产物路径
